language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: ENABLEDEBUG=true
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: VISHIDDEN=true
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 CC=gcc CXX=g++ VISHIDDEN=true
      compiler: clang
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 VISHIDDEN=true NOF77=true
      compiler: clang
    - os: osx
      osx_image: xcode10
      env: OSX=10.13 CC=gcc CXX=g++ ENABLEDEBUG=true
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      env: OSX=10.12 CC=gcc CXX=g++
      compiler: clang

before_script:
  - if [[ "$TRAVIS_OS_NAME $CC" == "osx gcc" ]]; then brew update; brew install bash gcc; brew link --overwrite gcc; gfortran --version; fi
  - export VISHIDDEN=${VISHIDDEN:-false}
  - export NOF77=${NOF77:-false}
  - export ENABLEDEBUG=${ENABLEDEBUG:-false}

script:
  - git clone --branch autotools-update --depth 1 https://github.com/coin-or-tools/ThirdParty-ASL
  - pushd ThirdParty-ASL && ./get.ASL && ./configure --prefix=$HOME/install && make && make install && popd
  - if $NOF77 ; then echo "Skipping Mumps build." ; else git clone --branch autotools-update --depth 1 https://github.com/coin-or-tools/ThirdParty-Mumps ; pushd ThirdParty-Mumps && ./get.Mumps && ./configure --prefix=$HOME/install && make && make install && popd ; fi
  - mkdir build
  - pushd build
  - if $VISHIDDEN ; then export CFLAGS="-fvisibility=hidden -DNDEBUG" ; fi
  - if $VISHIDDEN ; then export CXXFLAGS="-fvisibility=hidden -DNDEBUG" ; fi
  - export CFGFLAGS=""
  - if $NOF77 ; then CFGFLAGS="$CFGFLAGS --disable-f77" ; fi
  - if $ENABLEDEBUG ; then CFGFLAGS="$CFGFLAGS --enable-debug" ; fi
  - ../configure --prefix=$HOME/install $CFGFLAGS
  - make
  - if $NOF77 ; then echo "skip test as no linear solver" ; else make test ; fi
  - make install
